# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-11 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20160311_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='cat_type',
            new_name='caterory_type',
        ),
        migrations.RenameField(
            model_name='bookcategorytype',
            old_name='cat_type',
            new_name='caterory_type',
        ),
    ]
